# When a new Release is created, deploy relevant
# files to each of the generated repos.
name: Deploy User Guide

on:
  release:
    types: [published]

jobs:
  framework:
    name: Deploy to userguide
    if: (github.repository == 'codeigniter4/CodeIgniter4')
    runs-on: ubuntu-latest
    steps:
      - name: Identify
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "${GITHUB_ACTOR}"

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: source

      - name: Checkout target
        uses: actions/checkout@v3
        with:
          repository: codeigniter4/userguide
          token: ${{ secrets.ACCESS_TOKEN }}
          path: userguide

      - name: Install Sphinx
        run: |
          sudo apt install python3-sphinx
          sudo pip3 install sphinxcontrib-phpdomain
          sudo pip3 install sphinx_rtd_theme

      - name: Chmod
        run: chmod +x ./source/.github/scripts/deploy-userguide

      - name: Deploy
        run: ./source/.github/scripts/deploy-userguide ${GITHUB_WORKSPACE}/source ${GITHUB_WORKSPACE}/userguide ${GITHUB_REF##*/}

      - name: Release
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.ACCESS_TOKEN}}
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: 'userguide',
              tag_name: release.data.tag_name,
              name: release.data.name,
              body: release.data.body
            })
